### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by saianwork** [PiSimo/BitcoinForecast#14]
What's the purpose of running grabber 2/3 days to get the new data when I can just fetch it all in a second?

Could you explain your point of view please?

thanks mate

**Comment by saianwork** [comment]
Sorry dude I just went through it again and I just got it... Hehe sorry cheers

**Comment by saianwork** [comment]
There is one issue tho. the generated data with grabber.py is not the same than the dataset.csv.
could you help ?

**Comment by PiSimo** [comment]
Hi, 
because I've updated it, and didn't collect more data since then. 
If you collect new data I'll be happy to upload it.

**Comment by saianwork** [comment]
If you give me the way you made the pattern I’d do it because I’m working on it.  What I mean. The way  Graber writes in files isn’t the same than dataset.csv so if u run training on the new generated file it won’t work. I’ll find a way and let you know. I saw someone corrected the issue in a fork. Cheers.

**Comment by PiSimo** [comment]
You just need to delete the old dataset.csv and start grabber.py, then you can train the net on your new data.

**Comment by saianwork** [comment]
If I want to change the keys values 
`keys = ["price_usd","24h_volume_usd","market_cap_usd","available_supply","total_supply","percent_change_1h","percent_change_24h","percent_change_7d"]`

what else should I change in the code can you give me this hint. how do I process `net.fit(np.array(data[:el]),np.array(labels[:el]),epochs=epochs,batch_size=300)` for example if I only want. `keys = ["high", "low", "close"]` in network.py 
I'm trying to learn. I have a good idea about what I want to do but I'm training for now.

**Comment by PiSimo** [comment]
You should change the network parameters in the buildNet(); for example if you change the number of features to 3 replace the 12s with 3.

**Comment by saianwork** [comment]
Oh cool ok I'm starting to understand now. many thanks. Is there a way we can get in touch privately? email or so? I got an offer for you.

**Comment by PiSimo** [comment]
You can text me on my e-mail.

**Comment by zmfb039** [comment]
Hi guys, I have read through the comments here and i'm still a bit confused about the correct order in the original dataset.csv compared to the grubber.py.  The original dataset.csv appears to have a percentage number in the first column.  I have run the grubber for a few days and want to ensure I recreate the exact order.   Can you please help? Thanks
