### ISSUE TITLE
Predicted Price

### ISSUE THREAD

**Issue by delta7014** [PiSimo/BitcoinForecast#15]
I seem to get the same predicted price every-time whether I retrain the model or not.

**Comment by PiSimo** [comment]
Have you collected new data ?

**Comment by delta7014** [comment]
No I was using the included dataset

**Comment by delta7014** [comment]
Should I retrain using new data from grabber.py?

**Comment by PiSimo** [comment]
Yes, because the data changed a lot.

**Comment by delta7014** [comment]
Alright then thx
