### ISSUE TITLE
change 9min to (15min or 30min)?

### ISSUE THREAD

**Issue by wkshare** [PiSimo/BitcoinForecast#3]
You can choose your own configuration time
How do I change the code?

**Comment by PiSimo** [comment]
In network.py  the variable wait_time holds how many seconds the main loop has to wait before getting new values and then predict new price.
In grabber.py time.sleep().
But the current network's weights are trained on 9m intervals, so you should collect new data using grabber.py and then train the network on it.

**Comment by wkshare** [comment]
thks, i got
