### ISSUE TITLE
dataset.csv 

### ISSUE THREAD

**Issue by wkshare** [PiSimo/BitcoinForecast#4]
Can I have dataset.csv format?

**Comment by wkshare** [comment]
How to get the new dataset.csv @PiSimo

**Comment by PiSimo** [comment]
"price_usd","24h_volume_usd","market_cap_usd","available_supply","total_supply","percent_change_1h","percent_change_24h","percent_change_7d"," volume","vwap","sell","buy","15m"

**Comment by PiSimo** [comment]
To get an updated dataset.csv you have to run grabber.py for a long time. The best would be running it on a raspberry pi and get the dataset after some time.

**Comment by wkshare** [comment]
Would you like to provide a copy of the latest dataset.csv? ：） @PiSimo

**Comment by PiSimo** [comment]
I would like, but the last one I collected was the one I uploaded.  Sorry : (

**Comment by wkshare** [comment]
Okay
